### ISSUE TITLE
align /journeys signature with the other transport.rest APIs

### ISSUE THREAD

**Issue by derhuerst** [juliuste/meinfernbus-rest#2]
This API currently has this format:

```
https://1.flixbus.transport.rest/journeys/?origin=…&destination=…&date=…
                                         ^                         ^
```

Whereas the other APIs have this format:

```
https://2.vbb.transport.rest/journeys?from=…&to=…&when=…
                                     ^             ^
```

We should decide on a common signature and use it among all of the APIs. **This would be a breaking change.**

**Comment by derhuerst** [comment]
I've shut it off now.

**Comment by juliuste** [comment]
> I've shut it off now.

You've shut off what now? 😄

**Comment by derhuerst** [comment]
Sorry. I've shut off `vbb.transport.rest`.
